"""add total_amount currency tax to receipts

Revision ID: 862561f99e7c
Revises: a99fd9eceaaf
Create Date: 2026-09-16 16:28:34.923902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '862561f99e7c'
down_revision: Union[str, Sequence[str], None] = 'a99fd9eceaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('total_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('receipts', sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False))
    op.add_column('receipts', sa.Column('tax', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'tax')
    op.drop_column('receipts', 'currency')
    op.drop_column('receipts', 'total_amount')
    # ### end Alembic commands ###
