"""add receipt status field

Revision ID: 84c9ad842adf
Revises: ecfb55f0878a
Create Date: 2026-09-15 11:01:48.941542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84c9ad842adf'
down_revision: Union[str, Sequence[str], None] = 'ecfb55f0878a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    receipt_status = sa.Enum(
        'uploaded', 'processing', 'review', 'submitted', 'approved', 'rejected', name='receipt_status'
    )
    receipt_status.create(op.get_bind(), checkfirst=True)
    op.add_column('receipts', sa.Column('status', receipt_status, server_default='uploaded', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'status')
    sa.Enum(name='receipt_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
