"""make receipt reviewer_id required

Revision ID: a99fd9eceaaf
Revises: e8716ae3e705
Create Date: 2026-09-16 10:21:04.223352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a99fd9eceaaf'
down_revision: Union[str, Sequence[str], None] = 'e8716ae3e705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'reviewer_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('receipts', 'reviewer_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
